---
title: "Lab 11 - Data, Aesthetics, & Geometries"
author: "Ignacio Cabezudo"
date: "November 9, 2017"
output: pdf_document
---

Complete the following exercises below. Knit together the PDF document and commit both the Lab 11 RMD file and the PDF document to Git. Push the changes to GitHub so both documents are visible in your public GitHub repository. 

1. Which variables in your dataset are you interested in visualizing? Describe the level of measurement of these variables and what type of geography you think is appropriate to represent these variables. Give your reasoning for choosing the `geom_()` you selected. 

The variables that will be visuallized will be nkill, iyear from the GTD dataset & year, country from the IMF dataset.

2. Is your data in the proper format to visualize the data in the way you want? Why or why not? *If you need/want to change the structure of your data, do it below.* 

I don't know, I'm having trouble deciding on this. Will no more after our meeting today. 



3. Create at least two different exploratory plots of the variables you chose using the skills we covered in class today. What types of mapping aesthetics did you choose and why? What do these plots tell you about your data?

```{R Plot 1}
library(ggplot2)
library(tidyverse)
library(hexbin)
library(readxl)

gtd_filter <- c("country_txt", "nkill", "iyear", "imonth")
gtd_full <- read_csv("GTD FULL DB.csv")
IMF_Real_GDP_Growth <- read_excel("IMF Real GDP Growth.xls")


#Set the ranges for the data using filter
plotTerror <- filter(gtd_full, country_txt == c("Nigeria", "Niger", "Chad", "Cameroon") & iyear > 2000 & nkill > 1)
plotTerror <- select(plotTerror,gtd_filter)

#Fix the GDP growth data 
temp <- gather(IMF_Real_GDP_Growth, key = Year, value = RGDP, ...=-'X__1')

#Rename columns to setup keys for join
names(temp)[names(temp) == 'X__1'] <- 'Countries'
names(plotTerror)[names(plotTerror) == 'country_txt'] <- 'Countries'
names(plotTerror)[names(plotTerror) == 'iyear'] <- "Year"

#Join the two datasets

joinT <- merge(plotTerror, temp, by = c("Countries", "Year"))

#Make some plots

ggplot(joinT, aes(x = Year, y = log(nkill), col = Countries )) +
  geom_jitter() 
 

ggplot(joinT, aes(x = Year, y = RGDP, col = Countries)) +
  geom_line()






```

4. Create at least three variations of the plots you've already made by modifying some of the arguments we covered in class (i.e. `position`, `scale`, `size`, `linetype` etc.). Do any of these modifications help you understand your data better? Why or why not? Do any of them create a misleading interpretation of the relationships between your variables? If yes, how so?

```{R Plots Modified}

ggplot(joinT, aes(x = Year, y = log(nkill))) +
  geom_jitter()+
  facet_grid(. ~ Countries)
 
 

ggplot(joinT, aes(x = Year, y = RGDP, col = Countries)) +
  geom_line() +
  scale_x_continuous(
    name = "Years", 
    limits = c(2000, 2017)) 



```







5. From the plots you've created thus far, do any of them seem appropriate for a general audience? Why or why not? If so, what do you think you'd still need to do to make them more suitable as explanatory visualizations? 


Not really, nothing looks good or make sense yet for anyone but me. I'm going to try and do some stats manipulation of the data to see if I can find a better solution. 



