---
title: "Terrorism RGDP Codebook"
author: "Ignacio Cabezudo"
date: "November 14, 2017"
output: pdf_document
---

Study Design

  The purpose of this study is to search for a correlation between conflict events involving casualties caused by terror events and the economic growth potential of a country's population. The countries will be Nigeria, Niger, Chad, and Cameroon. Economic growth potential will be measured using the International Monetary Fund's (IMF) Real GDP Growth annual percent change index. The conflict events and death tolls are sourced from the National Consortium for the Study of Terrorism and Responses to Terrorism's (START) Global Terrorism Database. 

Data Files:
GTD Database - 
Entries - 170,350
Variables - 135

Each entry consists of data on one terror event. These terror events are found through a machine learning algorithm that sifts through thousands of news article per month. The events that are chosen are sent to a team of researchers at the University of Maryland. The teams are grouped by several specialties and verify the information to the best of their abilities before they are added to the database. 


National Consortium for
the Study of Terrorism and Responses to Terrorism (START). (2017). Global Terrorism Database [Data file]. Retrieved from https://www.start.umd.edu/gtd

International Monetary Fund World Economic Outlook (IMF). (2017). World Economic
Outlook Database [Data file] Retrieved from
http://www.imf.org/external/pubs/ft/weo/2017/02/weodata/index.aspx

The years being investigated will begin in 1991 and continue until 2017. 

Sampling

The group of people represented in this study are those victims of terrorist attacks in the selected countries. They are represented by the variable TOTALCAS, which contains the total casualties per year. It should be noted that the nwound variable contains both attackers and victims in its count. 


Variable Index

Countries 
(countries)
The country an attack has taken place

Real Gross Domestic Product
(RGDP)
The RGDP differs from the nominal GDP in that it has been adjusted for inflation. GDP is the total value of goods produced and services provided in a country during one year.

Total Casualties
(TOTALCAS)
Total casualty count per year. This variable was created by first finding the sum of nkill and nwound for each event in the database, and then finding the sum of that total by year. 


Global Terrorism Database
Entry descriptions taken directly from their codebook: 
Total Number of Fatalities
(nkill)
Numeric Variable

This field stores the number of total confirmed fatalities for the incident. The
number includes all victims and attackers who died as a direct result of the incident. Where there is evidence of fatalities, but a figure is not reported or it is too vague to be of use, this field remains blank. If information is missing regarding the number of victims killed in an attack, but perpetrator fatalities are known, this value will reflect only the number of perpetrators who died as a result of the incident. Likewise, if information on the number of perpetrators killed in an attack is missing, but victim fatalities are known, this field will only report the number of victims killed in the incident. Where several independent sources report different numbers of casualties, the database will usually reflect the number given by the most recent source. However, the most recent source will not be used if the source itself is of questionable validity
or if the source bases its casualty numbers on claims made by a perpetrator group. When there are several “most recent” sources published around the same time, or there are concerns about the validity of a recent source, the majority  figure will be used. Where there is no majority figure among independent sources, the database will record the lowest proffered fatality figure, unless that figure comes from a source of questionable validity or there is another compelling reason to do otherwise. Conflicting reports of fatalities will be noted in the
“Additional Notes” field.

Note: Preservation of Statistical Accuracy
When several cases are linked together, sources sometimes provide a cumulative
fatality total for all of the events rather than fatality figures for each incident. In such cases, the preservation of statistical accuracy is achieved by distributing fatalities across the linked incidents. It will be noted in the “Additional Notes” field whenever cumulative totals are divided across multiple events. This method for preserving statistical accuracy is also used for calculating the values for the following fields when individual event totals are unknown: “Number of U.S. Fatalities,” “Number of Perpetrator Fatalities,” “Total Number of Injured,” “Number of U.S. Injured,” and “Number of Perpetrators Injured.”

Total Number of Injured
(nwound)
Numeric Variable
This field records the number of confirmed non-fatal injuries to both perpetrators and victims. It follows the conventions of the “Total Number of Fatalities” field described above.

Year

(iyear)
Numeric Variable
This field contains the year in which the incident occurred. In the case of incident(s) occurring over an extended period, the field will record the year  when the incident was initiated. 


